version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Zurich
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Europe/Zurich
    groups:
      github-actions:
        patterns:
          - "*"
